### Récupération de toutes les attaques
GET http://localhost:8084/attack


### Création d'une attaque (cas réussi)
POST http://localhost:8084/attack
Content-Type: application/json

{
  "targetId": 1
}


### Création d'une attaque avec une cible inexistante (cas qui échoue)
POST http://localhost:8084/attack
Content-Type: application/json

{
  "targetId": 9999
}


### Lecture d'une attaque par ID (cas réussi)
GET http://localhost:8084/attack/1


### Lecture d'une attaque inexistante (cas qui échoue)
GET http://localhost:8084/attack/999


### Suppression d'une attaque par ID (cas réussi)
DELETE http://localhost:8084/attack/1


### Suppression d'une attaque inexistante (cas qui échoue)
DELETE http://localhost:8084/attack/999


### Mise à jour des notes d'une attaque (cas réussi)
PATCH http://localhost:8084/attack/2/notes
Content-Type: application/json

Nouvelle note pour l'attaque


### Mise à jour des notes d'une attaque inexistante (cas qui échoue)
PATCH http://localhost:8084/attack/999/notes
Content-Type: application/json

Nouvelle note


### Mise à jour du serveur d'une attaque (cas réussi)
PATCH http://localhost:8084/attack/2/server
Content-Type: application/json

1


### Mise à jour du serveur avec un serveur inexistant ou non validé (cas qui échoue)
PATCH http://localhost:8084/attack/2/server
Content-Type: application/json

9999


### Mise à jour de l'exploit d'une attaque (cas réussi)
PATCH http://localhost:8084/attack/2/exploit
Content-Type: application/json

1


### Mise à jour de l'exploit avec un exploit inexistant ou non validé (cas qui échoue)
PATCH http://localhost:8084/attack/2/exploit
Content-Type: application/json

9999


### Lancement d'une attaque (cas réussi)
POST http://localhost:8084/attack/2/launch


### Lancement d'une attaque déjà en cours ou terminée (cas qui échoue)
POST http://localhost:8084/attack/2/launch


### Mise à jour du résultat d'une attaque (cas réussi)
POST http://localhost:8084/attack/2/result
Content-Type: application/json

{
  "status": "TERMINEE"
}


### Mise à jour du résultat avec un statut incorrect (cas qui échoue)
POST http://localhost:8084/attack/2/result
Content-Type: application/json

{
  "status": "INVALIDE"
}


### Suppression des attaques liées à une cible (cas réussi)
DELETE http://localhost:8084/attack/targets/2


### Suppression des attaques liées à une cible inexistante (cas réussi mais sans effet visible)
DELETE http://localhost:8084/attack/targets/999


### Suppression des attaques liées à un serveur (cas réussi)
DELETE http://localhost:8084/attack/servers/5


### Suppression des attaques liées à un exploit (cas réussi)
DELETE http://localhost:8084/attack/exploits/1
