### Creation de la cible
POST http://localhost:8082/targets
Content-Type: application/json

{
  "companyName": "CyberCorp",
  "domain": "cybercorp.com",
  "location": "Paris, France",
  "employees": 50,
  "revenue": 1000000
}

### Création d'une attaque
POST http://localhost:8084/attack
Content-Type: application/json

{
  "targetId": 1
}

### Récupération de toutes les attaques
GET http://localhost:8084/attack

### Read all
GET http://localhost:8082/targets



### Récupération de toutes les attaques
GET http://localhost:8084/attack



### Test création d'un serveur
POST http://localhost:8083/servers
Content-Type: application/json

{
  "ipAddress": "192.168.1.10",
  "targetId": 1,
  "serverType": "web",
  "technology": "Apache"
}
//faire 2 fois  pour avoir 2 serveurs

### Test lecture d'un serveur (par ID)
GET http://localhost:8083/servers/2

### Test modification d'un serveur
PUT http://localhost:8083/servers/2
Content-Type: application/json

{
  "id": 2,
  "ipAddress": "192.168.1.20",
  "targetId": 1,
  "serverType": "web",
  "technology": "Nginx",
  "validated": false
}

### Test suppression d'un serveur
DELETE http://localhost:8083/servers/1

### Test lecture du serveur supprimé (par ID)
GET http://localhost:8083/servers/1


### Test validation d'un serveur
PATCH http://localhost:8083/servers/2/validate

### Test récupération de serveurs associés à une cible
GET http://localhost:8083/servers/target/1

### Test suppression de serveurs associés à une cible
DELETE http://localhost:8083/servers/target/1
