openapi: 3.0.3
info:
  title: Vinci Cyber Intelligence Exploit service
  description: | 
    Microservice de gestion des exploits. Ce service est conçu afin de permettre aux hackers de 
    répertorier des vulnérabitlités connues et les méthodes pour les exploiter. 
    Les utilisateurs peuvent consulter un liste détaillant des exploits et également 
    effectuer des recherches en fonction de l'auteur ou du type de serveur affecté. 
    Chaque utilisateur peut créer et supprimer des exploits, ainsi que modifier la description 
    et le guide de ses derniers.
    Si un utilisateur possède le rôle d'adminstrateur, il aura la capacité de valider un exploit.
  version: 1.0.0
servers:
  - url: 'http://localhost:9001'
    description: Development server
paths:

  /exploits:
    get:
      summary: Lire les détails de tous les exploits
      responses:
        200:
          description: Retourne la liste de tous les exploits
          content:
            'application/json':
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/exploit'

    post:
      summary: Créer un exploit
      requestBody:
        description: Données de l'exploit à créer
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/exploit'
      responses:
        409:
          description: Un exploit existe déjà avec cet id
        201:
          description: L'exploit a été créé


  /exploits/author/{author}:
    parameters:
      - name: author
        in: path
        description: Nom de l'auteur de l'exploit
        required: true
        schema:
          type: string
          example: Nicolas Jackson

    get:
      summary: Lire les détails d'un exploit sur base de son auteur
      responses:
        404:
          description: Aucun exploit n'a été trouvé pour cet auteur
        200:
          description: Retounre les données de l'exploit correspondant
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/exploit'


  /exploits/server/{server_type}:
    parameters:
      - name: server_type
        in: path
        description: Type de serveur
        required: true
        schema:
          type: string
          example: Backup

    get:
      summary: Lire les détails d'un exploit sur base de son type de serveur
      responses:
        404:
          description: Aucun exploit n'a été trouvé pour ce type de serveur
        200:
          description: Retounre les données de l'exploit correspondant
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/exploit'

  /exploits/{id}:
    parameters:
      - name: id
        in: path
        description: Identifiant de l'exploit
        required: true
        schema:
          type: integer
          example: 1

    delete:
      summary: Supprimer un exploit sur base de son identifiant
      responses:
        404:
          description: Aucun exploit n'a été trouvé pour cet identifiant
        200:
          description: L'exploit a été supprimé

    patch:
      summary: Valider un exploit
      requestBody:
        description: Modification de l'état de validation de l'exploit
        content:
          'application/json':
            schema:
              type: object
              properties:
                validated:
                  type: boolean
                  description: Validation d'un exploit
      responses:
        404:
          description: Aucun exploit n'a été trouvé pour cet identifiant
        200:
          description: L'exploit a été validé


  /exploits/description/{id}:
    parameters:
      - name: id
        in: path
        description: Identifiant de l'exploit
        required: true
        schema:
          type: integer
          example: 1

    patch:
      summary: Modifier la description d'un exploit
      requestBody:
        description: Nouvelle description de l'exploit correspondante
        content:
          'application/json':
            schema:
              type: object
              properties:
                description:
                  type: string
                  description: Description d'un exploit
      responses:
        404:
          description: Aucun exploit n'a été trouvé pour cet identifiant
        200:
          description: La description de l'exploit a été modifiée


  /exploits/guide/{id}:
    parameters:
      - name: id
        in: path
        description: Identifiant de l'exploit
        required: true
        schema:
          type: integer
          example: 1

    patch:
      summary: Modifier le guide d'un exploit
      requestBody:
        description: Nouvelle guide de l'exploit correspondante
        content:
          'application/json':
            schema:
              type: array
              items:
                type: object
                properties:
                  step_number:
                    type: integer
                    description: Numéro de l'étape
                  instruction:
                    type: string
                    description: Instruction spécifique pour cette étape
      responses:
        404:
          description: Aucun exploit n'a été trouvé pour cet identifiant
        200:
          description: La description de l'exploit a été modifiée


components:
  schemas:
    exploit:
      type: object
      properties:
        exploit_id:
          type: integer
          description: Identifiant de l'exploit
        name:
          type: string
          description: Nom de l'exploit
        description:
          type: string
          description: Description détaillée de l'exploit
        author:
          type: string
          description: Auteur de l'exploit
        server_type:
          type: string
          description: Type de serveur
        guide:
          type: array
          items:
            type: object
            properties:
              step_number:
                type: integer
                description: Numéro de l'étape
              instruction:
                type: string
                description: Instruction spécifique pour cette étape
        validated:
          type: boolean
          description: Exploit validé ou non par l'administrateur
      example:
        exploit_id: 1
        name: Buffer Overflow Attack
        description: Exploit visant une vulnérabilité de débordement de mémoire tampon sur les serveurs.
        author: Nicolas Jackson
        server_type: Linux
        guide:
          - step_number: 1
            instruction: "Identifier la taille du tampon."
          - step_number: 2
            instruction: "Injecter un code malveillant."
          - step_number: 3
            instruction: "Exécuter le payload."
        validated: false