openapi: 3.0.3
info:
  title: Vinci Cyber Intelligence Server Service
  description: Micro service de gestion des serveurs pour le projet Vinci Cyber Intelligence. Permet de créer, consulter, modifier et supprimer des serveurs.
  version: 1.0.0
servers:
  - url: 'http://localhost:9003'
    description: Development server
paths:
  /servers:
    get:
      summary: Consulter tous les serveurs
      description: |
        Permet de récupérer la liste des serveurs associés aux différentes cibles dans le système.

        **Erreurs possibles** :
          - `404 Not Found` : Si aucun serveur n'est trouvé.

      responses:
        '200':
          description: Liste des serveurs récupérée avec succès
        '404':
          description: Aucun serveur trouvé

    post:
      summary: Créer un nouveau serveur
      description: |
        Permet de créer un nouveau serveur en fournissant les informations requises dans le corps de la requête. Cette opération met également à jour le nombre de serveurs pour l'entreprise associée.

        **Paramètres** : Aucun paramètre dans l'URL. Les informations du serveur sont envoyées dans le corps de la requête.

        **Préconditions** :
          - Toutes les informations nécessaires pour créer le serveur doivent être fournies.
        
        **Corps de la requête** :
          - `ip` (obligatoire) : L'adresse IP unique du serveur.
          - `entreprise` (obligatoire) : Le nom de l'entreprise à laquelle est associé le serveur.
          - `type` (obligatoire) : Le type de serveur (web, base de données, etc.).
          - `technology` (obligatoire) : La technologie utilisée par le serveur (ex. : apache).
          - `valid` (optionnel) : Statut de validation du serveur, par défaut `false` si non spécifié.

        **Erreurs possibles** :
          - `400 Bad Request` : Si les données fournies ne sont pas valides.
          - `409 Conflict` : Si un serveur avec la même adresse IP existe déjà.
      requestBody:
        description: Données du serveur à créer.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/server'
      responses:
        '201':
          description: Serveur créé avec succès
        '400':
          description: Données invalides fournies
        '409':
          description: Serveur avec cette adresse IP déjà existant

  /servers/{ip}:
    parameters:
      - name: ip
        in: path
        required: true
        description: Adresse IP du serveur (obligatoire)
        schema:
          type: string
    get:
      summary: Récupérer les détails d'un serveur
      description: |
        Permet de récupérer les informations détaillées d'un serveur spécifique à l'aide de son adresse IP.

        **Paramètres** :
          - `ip` (obligatoire) : L'adresse IP du serveur à récupérer.

        **Préconditions** :
          - L'adresse IP doit correspondre à un serveur existant dans le système.

        **Erreurs possibles** :
          - `404 Not Found` : Si aucun serveur avec cette adresse IP n'est trouvé.
      responses:
        '200':
          description: Détails du serveur récupérés avec succès
        '404':
          description: Aucun serveur trouvé pour cette adresse IP

    put:
      summary: Mettre à jour un serveur
      description: |
        Permet de mettre à jour les informations d'un serveur existant, en modifiant ses propriétés telles que le type, la technologie et le statut de validation.

        **Paramètres** :
          - `ip` (obligatoire) : L'adresse IP du serveur à mettre à jour.

        **Préconditions** :
          - L'adresse IP doit correspondre à un serveur existant.
          - Seuls les administrateurs peuvent modifier le champ `valid`.

        **Corps de la requête** :
          - `entreprise` (optionnel) : Nom de l'entreprise hébergeant le serveur.
          - `type` (optionnel) : Type de serveur.
          - `technology` (optionnel) : Technologie utilisée.
          - `valid` (optionnel) : Statut de validation (réservé aux administrateurs).

        **Erreurs possibles** :
          - `400 Bad Request` : Si les données fournies pour la mise à jour ne sont pas valides.
          - `403 Forbidden` : Accès refusé pour la modification du champ `valid` si l'utilisateur n'est pas administrateur.
          - `404 Not Found` : Si aucun serveur avec cette adresse IP n'est trouvé.
      requestBody:
        description: Données du serveur à mettre à jour.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/server'
      responses:
        '200':
          description: Serveur mis à jour avec succès
        '400':
          description: Données invalides fournies pour la mise à jour
        '403':
          description: Accès refusé pour la modification du statut de validation
        '404':
          description: Aucun serveur trouvé pour cette adresse IP

    delete:
      summary: Supprimer un serveur
      description: |
        Supprime un serveur existant en fonction de son adresse IP. La suppression d'un serveur ajuste automatiquement le nombre de serveurs de l'entreprise associée.

        **Paramètres** :
          - `ip` (obligatoire) : L'adresse IP du serveur à supprimer.

        **Préconditions** :
          - L'adresse IP doit correspondre à un serveur existant.

        **Erreurs possibles** :
          - `404 Not Found` : Si aucun serveur avec cette adresse IP n'est trouvé.
      responses:
        '200':
          description: Serveur supprimé avec succès
        '404':
          description: Aucun serveur trouvé pour cette adresse IP

  /servers/{ip}/validate:
    patch:
      summary: Valider un serveur
      description: |
        Permet à un utilisateur avec des privilèges administratifs de valider un serveur spécifique, en utilisant son adresse IP.

        **Paramètres** :
          - `ip` (obligatoire) : L'adresse IP du serveur à valider.

        **Préconditions** :
          - Seuls les administrateurs peuvent effectuer cette action.
          - L'adresse IP doit correspondre à un serveur existant.

        **Erreurs possibles** :
          - `403 Forbidden` : Accès refusé si l'utilisateur n'est pas administrateur.
          - `404 Not Found` : Si aucun serveur avec cette adresse IP n'est trouvé.
      responses:
        '200':
          description: Serveur validé avec succès
        '403':
          description: Accès refusé pour validation du serveur
        '404':
          description: Aucun serveur trouvé pour cette adresse IP

components:
  schemas:
    server:
      description: |
        Un serveur est une machine associée à une cible sur laquelle une attaque peut être réalisée.
        Il est associé à une cible et contient des informations telles que l'adresse IP, 
        l'entreprise hébergeante, le type de serveur, la technologie utilisée et le statut de validation.
      type: object
      properties:
        ip:
          type: string
          description: L'adresse IP du serveur
        company:
          type: string
          description: L'entreprise hébergeant le serveur
        type:
          type: string
          description: Le type de serveur (web, base de données, etc.)
        technology:
          type: string
          description: La technologie utilisée
        validated:
          type: boolean
          description: Le serveur est-il validé ?
      example:
        ip: '246.250.160.253'
        company: 'Vinci'
        type: 'web'
        technology: 'apache'
        validated: true
