openapi: 3.0.3
info:
  title: Vinci Cyber Intelligence Target service
  description: |
    Microservice de gestion des cibles. Ce service permet aux hackers d'enregistrer des cibles potentielles pour leurs attaques. 
    Chaque cible doit être décrite avec précision, incluant le nom de l’entreprise, son nom de domaine, sa localisation, son nombre d’employés, 
    son nombre de serveurs, et son chiffre d’affaires. Un utilisateur administrateur doit pouvoir créer une nouvelle cible, initialement avec un 
    nombre de serveurs à zéro. Il peut ensuite modifier son nom de domaine, son nombre d’employés ou son chiffre d’affaires. 
    Il peut également supprimer une cible. Tous les utilisateurs peuvent consulter les informations des cibles. 
    Ils doivent également pouvoir rechercher des cibles en fonction du nombre de serveurs ou d’un chiffre d’affaires minimal. 
    Par ailleurs, il est possible de trouver les cibles qui sont co-localisées. En effet, si un hacker a déjà compromis les serveurs de l’entreprise A, 
    et qu’on sait que ses services tournent sur la même machine (hébergement mutualisé) que ceux de la société B, il pourrait vouloir lancer une attaque sur la société B.
  version: 1.0.0
servers:
  - url: 'http://localhost:9002'
    description: Development server
paths:

  /targets:
    get:
      summary: Lire toutes les cibles
      description: |
        Cette opération permet de récupérer la liste de toutes les cibles enregistrées dans le système. 
        Les utilisateurs peuvent filtrer les résultats en fonction du nombre minimal de serveurs ou d'un chiffre d'affaires minimal.
      parameters:
        - name: nbServers
          in: query
          description: Nombre minimal de serveurs
          required: false
          schema:
            type: integer
            example: 10
        - name: revenue
          in: query
          description: Chiffre d'affaires minimal
          required: false
          schema:
            type: integer
            example: 100000
      responses:
        200:
          description: Retourne la liste de toutes les cibles
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/target'

    post:
      summary: Créer une nouvelle cible
      description: |
        Cette opération permet à un utilisateur administrateur de créer une nouvelle cible. 
        La cible est initialement créée avec un nombre de serveurs à zéro. Les informations nécessaires incluent le nom de l'entreprise, 
        son nom de domaine, sa localisation, son nombre d'employés et son chiffre d'affaires.
      requestBody:
        description: Données de la cible à créer
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/target'
      responses:
        201:
          description: La cible a été créée
        401:
          description: L'utilisateur n'est pas un administrateur

  /targets/{id}:
    parameters:
      - name: id
        in: path
        description: ID de la cible
        required: true
        schema:
          type: integer
          example: 1

    get:
      summary: Lire les détails d'une cible
      description: |
        Cette opération permet de récupérer les détails d'une cible spécifique en utilisant son identifiant unique. 
        Si la cible n'est pas trouvée, une réponse 404 est retournée.
      responses:
        404:
          description: Aucune cible n'a été trouvée pour cet ID
        200:
          description: Retourne les détails de la cible
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/target'

    delete:
      summary: Supprimer une cible
      description: |
        Cette opération permet à un utilisateur administrateur de supprimer une cible spécifique en utilisant son identifiant unique. 
        Si la cible n'est pas trouvée, une réponse 404 est retournée.
      responses:
        404:
          description: Aucune cible n'a été trouvée pour cet ID
        200:
          description: La cible a été supprimée

    patch:
      summary: Modifier une cible
      description: |
        Cette opération permet à un utilisateur administrateur de modifier les informations d'une cible spécifique en utilisant son identifiant unique. 
        Les informations modifiables incluent le nom de domaine, le nombre d'employés et le chiffre d'affaires. 
        Si la cible n'est pas trouvée, une réponse 404 est retournée.
      requestBody:
        description: Données de la cible à modifier
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/target'
      responses:
        404:
          description: Aucune cible n'a été trouvée pour cet ID
        401:
          description: L'utilisateur n'est pas un administrateur
        200:
          description: La cible a été modifiée

  /targets/colocated:
    get:
      summary: Trouver des cibles co-localisées
      description: |
        Cette opération permet de trouver des cibles qui sont co-localisées avec une entreprise déjà compromise. 
        Les utilisateurs doivent fournir le nom de l'entreprise déjà compromise pour obtenir la liste des cibles co-localisées.
      parameters:
        - name: companyName
          in: query
          description: Nom de l'entreprise déjà compromise
          required: true
          schema:
            type: string
            example: Entreprise A
      responses:
        200:
          description: Retourne la liste des cibles co-localisées
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/target'

components:
  schemas:
    target:
      type: object
      properties:
        id:
          type: integer
          description: Identifiant unique de la cible
        companyName:
          type: string
          description: Nom de l'entreprise
        domain:
          type: string
          description: Nom de domaine de la cible
        location:
          type: string
          description: Localisation de la cible
        nbEmployees:
          type: integer
          description: Nombre d'employés de la cible
        nbServers:
          type: integer
          description: Nombre de serveurs de la cible
        revenue:
          type: integer
          description: Chiffre d'affaires de la cible
      example:
        id: 1
        companyName: "My Company"
        domain: "mycompany.com"
        location: "Bruxelles"
        nbEmployees: 100
        nbServers: 15
        revenue: 210000