### Read all
GET http://localhost:8082/targets

### Create one
POST http://localhost:8082/targets
Content-Type: application/json

{
  "companyName": "CyberCorp",
  "domain": "cybercorp.com",
  "location": "Paris, France",
  "employees": 50,
  "revenue": 1000000
}

### Create one
POST http://localhost:8082/targets
Content-Type: application/json

{
  "companyName": "OtherCorp",
  "domain": "othercorp.com",
  "location": "Paris, France",
  "employees": 50,
  "revenue": 1000000
}

### Read one
GET http://localhost:8082/targets/1

### Update one
PUT http://localhost:8082/targets/1
Content-Type: application/json

{
  "id": 1,
  "companyName": "CyberCorpV2",
  "domain": "cybercorp.com",
  "location": "Bruxelles, Belgique",
  "employees": 50,
  "revenue": 1000000
}

### Création d'une attaque
POST http://localhost:8084/attack
Content-Type: application/json

{
  "targetId": 1
}

### Test création d'un serveur
POST http://localhost:8083/servers
Content-Type: application/json

{
  "ipAddress": "192.168.1.10",
  "targetId": 1,
  "serverType": "web",
  "technology": "Apache"
}

### Test création d'un serveur
POST http://localhost:8083/servers
Content-Type: application/json

{
  "ipAddress": "192.168.1.10",
  "targetId": 2,
  "serverType": "web",
  "technology": "Apache"
}

### Delete one
DELETE http://localhost:8082/targets/1

### Increase servers
PATCH http://localhost:8082/targets/1/increase-servers

### Decrease servers
PATCH http://localhost:8082/targets/1/decrease-servers

### Get colocated targets
GET http://localhost:8082/targets/colocated