### Read all
GET http://localhost:8082/targets

### Read all with all the filters
GET http://localhost:8082/targets?minServers=1&minRevenue=10000

### Read all with the min filter
GET http://localhost:8082/targets?minServers=1

### Read all with the max filter
GET http://localhost:8082/targets?minRevenue=10000

### Create one with every field needed
POST http://localhost:8082/targets
Content-Type: application/json

{
  "companyName": "CyberCorp",
  "domain": "cybercorp.com",
  "location": "Paris, France",
  "employees": 50,
  "revenue": 1000000
}

### Create one with one of the fields missing (companyName)
POST http://localhost:8082/targets
Content-Type: application/json

{
  "domain": "cybercorp.com",
  "location": "Paris, France",
  "employees": 50,
  "revenue": 1000000
}

### Create one
POST http://localhost:8082/targets
Content-Type: application/json

{
  "companyName": "OtherCorp",
  "domain": "othercorp.com",
  "location": "Paris, France",
  "employees": 50,
  "revenue": 1000000
}

### Create one that can be deleted
POST http://localhost:8082/targets
Content-Type: application/json

{
  "companyName": "ToDeleteCorp",
  "domain": "todelet.com",
  "location": "Paris, France",
  "employees": 50,
  "revenue": 1000000
}

### Read one target that exists
GET http://localhost:8082/targets/1

### Read one target that doens't exists
GET http://localhost:8082/targets/1234

### Update one with every field needed
PUT http://localhost:8082/targets/1
Content-Type: application/json

{
  "id": 1,
  "companyName": "CyberCorpV2",
  "domain": "cybercorp.com",
  "location": "Bruxelles, Belgique",
  "employees": 50,
  "servers": 100,
  "revenue": 1000000
}

### Update one with one of the field missing (domain)
PUT http://localhost:8082/targets/1
Content-Type: application/json

{
  "id": 1,
  "companyName": "CyberCorpV2",
  "location": "Bruxelles, Belgique",
  "employees": 50,
  "revenue": 1000000
}

### Update one that doesn't exists
PUT http://localhost:8082/targets/1234
Content-Type: application/json

{
  "id": 1234,
  "companyName": "CyberCorpV2",
  "domain": "cybercorp.com",
  "location": "Bruxelles, Belgique",
  "employees": 50,
  "revenue": 1000000
}

### Create one attack for the first target
POST http://localhost:8084/attack
Content-Type: application/json

{
  "targetId": 1
}

### Create one server for the first target
POST http://localhost:8083/servers
Content-Type: application/json

{
  "ipAddress": "192.168.1.10",
  "targetId": 1,
  "serverType": "web",
  "technology": "Apache"
}

### Create a second server for the first target (needed to test "colocated targets")
POST http://localhost:8083/servers
Content-Type: application/json

{
  "ipAddress": "192.168.1.10",
  "targetId": 2,
  "serverType": "web",
  "technology": "Apache"
}

### Delete one
DELETE http://localhost:8082/targets/1

### Delete one that doesn't exists
DELETE http://localhost:8082/targets/1234

### Increase servers for the first target
PATCH http://localhost:8082/targets/1/increase-servers

### Increase servers for a target that doesn't exist
PATCH http://localhost:8082/targets/1234/increase-servers

### Decrease servers for the first target
PATCH http://localhost:8082/targets/1/decrease-servers

### Decrease servers for a target that doesn't exist
PATCH http://localhost:8082/targets/1234/decrease-servers

### Get all colocated targets
GET http://localhost:8082/targets/colocated