### Récupération de toutes les attaques
GET http://localhost:8084/attack

---

### Création d'une attaque
POST http://localhost:8084/attack
Content-Type: application/json

{
  "targetId": 2
}

---

### Lecture d'une attaque par ID
GET http://localhost:8084/attack/12345

---

### Suppression d'une attaque par ID
DELETE http://localhost:8084/attack/12345

---

### Mise à jour des notes d'une attaque
PATCH http://localhost:8084/attack/12345/notes
Content-Type: application/json

{
  "notes": "Nouvelle note pour l'attaque."
}

---

### Mise à jour du serveur d'une attaque
PATCH http://localhost:8084/attack/12345/server
Content-Type: application/json

{
  "serverId": 67890
}

---

### Mise à jour de l'exploit d'une attaque
PATCH http://localhost:8084/attack/12345/exploit
Content-Type: application/json

{
  "exploitId": 98765
}

---

### Lancement d'une attaque
POST http://localhost:8084/attack/12345/launch

---

### Mise à jour du résultat d'une attaque
POST http://localhost:8084/attack/12345/result
Content-Type: application/json

{
  "status": "TERMINEE"
}

---

### Suppression des attaques liées à une cible
DELETE http://localhost:8084/attack/targets/54321

---

### Suppression des attaques liées à un serveur
DELETE http://localhost:8084/attack/servers/67890

---

### Suppression des attaques liées à un exploit
DELETE http://localhost:8084/attack/exploits/98765
